### PR TITLE
FI-2700: Initial version of FHIRPath service

### PR DESCRIPTION
**Pull request by dehall**
# Summary
Initial version of a FHIRPath evaluation service, just a straight copy of the relevant pieces of the inferno fhir-validator-wrapper https://github.com/inferno-framework/fhir-validator-wrapper with all of the validator pieces removed. Most of the files left here should be identical to the validator-wrapper version. The minor file changes that do exist include updating the name of the repo and project, simplifying some of the code where possible, and simplifying the dockerfile so it doesn't need 2 stages. 

This server hosts 2 endpoints:
- `/evaluate` which takes a request param of a FHIRPath string and a request body of a FHIR resource, and returns the results of evaluating that FHIRPath against that resource
- `/version` which reports the version of this service and the hl7 core library version

By default it runs on port 6789 but that can be changed with the `FHIRPATH_PORT` env var.

# Testing Guidance
Results should be the same for any request against this service as against the inferno validator-wrapper.

Sample request:

```
GET http://localhost:6789/evaluate?path=Patient.id

{"resourceType":"Patient", "id": "1"}
```

returns 
```
[
  {
    "type": "id",
    "element": "1"
  }
]
```

Since this is a brand new repo but all the code comes from a different one, consider using a diff tool to compare this repo to the inferno validator-wrapper to confirm what changed makes sense. (Personally I use kdiff3, available on mac via brew)

### CODE REVIEW

**Comment by karlnaden** [comment]
The best way for me to review this would be to fire it up and connect it to the PAS test kit. Is there an existing methodology for doing so? If not, does it make sense to develop it in parallel, or finish this initial work and then make adjustments based on any issues found when we go through that process? Thoughts @arscan @Jammjammjamm ?

**Comment by dehall** [comment]
@karlnaden since that test kit will be the primary user of this, at least in the short term, it is important that what we have here actually works with it. For the purposes of this PR/ticket maybe let's say done is "confirmed working as a drop-in replacement for the inferno validator-wrapper", and then if there are other enhancements/nice-to-haves requested, those can be separate items?

**Comment by karlnaden** [comment]
> For the purposes of this PR/ticket maybe let's say done is "confirmed working as a drop-in replacement for the inferno validator-wrapper"

To confirm "drop-in replacement" we need to actually integrate it into the PAS test kit then. I'm not sure I'm the right person to do that, or at least not in terms of setting up the infrastructure (putting this into inferno's docker services, creating a way in Ruby to connect to it), though I could try. Either way, I won't be able to get to it until after the connectathon / WGM next week.  @dehall do you think you'd be able to get the infrastructure pieces in place in a supporting inferno_core PR and then I can try to get it all working with PAS when I get back? Or is there a better division of labor?

**Review by karlnaden — APPROVED** [review]
Tested with the PAS test kit and validated that it is able to make fhirpath evaluation requests against the service

**Pull request merged**
